### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $config ]] in class Dymantic\InstagramFeed\Instagram

### ISSUE THREAD

**Issue by mahesh0055** [Dymantic/laravel-instagram-feed#15]
I tried using your package but now its giving this error. I can't seem to fix this issue. Help please.
![Capture](https://user-images.githubusercontent.com/39142355/102463120-c9249780-4072-11eb-91d0-666321477b6c.JPG)
e.

**Comment by michaeljoyner** [comment]
Hi @mahesh0055, I'm sorry you have run into this. Can you share a bit more info? The issue is that Laravel can't create an instance of the Instagram class, apparently because the config is missing. Can you check if config('instagram-feed') actually returns your config and not null?

**Comment by mahesh0055** [comment]
I did a fresh install and now it's working. Thank you  very much for your help.

**Comment by michaeljoyner** [comment]
That's great, thanks for letting me know.

**Comment by ley-288** [comment]
Hi i recieve the same error using php 7, version "^2.0", laravel 5.6

**Comment by michaeljoyner** [comment]
Hi @ley-288, please check that you have published the config file and that the values are getting correctly loaded.

**Comment by ley-288** [comment]
Hi yes 'vendor:publish' created the config file. i found a work-around to that error but it must be causing other issues because the key doesn't return on callback, and even following guide instructions, user returns to a 404 page.

<img width="700" alt="Screenshot 2022-04-07 at 15 49 13" src="https://user-images.githubusercontent.com/67469616/162214801-96189909-9583-49ff-a1b8-f7ef0c912fc2.png">

**Comment by ley-288** [comment]
Resolved issue completely. Just needed to manually add package to Bootstap cache packages.php and services.php!

**Comment by michaeljoyner** [comment]
That's great, thanks for letting me know. Sorry I wasn't able to provide more help.
