### ISSUE TITLE
Could not resolve host: graph.instagram.com 

### ISSUE THREAD

**Issue by erro-coffee** [Dymantic/laravel-instagram-feed#41]
I have had this package on my site for a while now and recently I get this error every now and then. It has resolved it self in the past but it also crashes my site when the error occurs so I am just wondering why. Not sure if its on my end, the package or Instagrams

`cURL error 6: Could not resolve host: graph.instagram.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) `

**Comment by michaeljoyner** [comment]
Hi @erro-coffee, this is a DNS issue, and not something you or I can do much about. Yesterday Facebook had major DNS issues which caused outages for them, which is why you received that error. I believe they have everything back up now, so it should be fine again.

However, the package is intended to be used safely so that your site doesn't crash when there is an error getting the feed. If you'd like to discuss that aspect of it, let me know.

**Comment by erro-coffee** [comment]
Thanks! I actually just realized after I posted this all of FB services were down, thus the issue. I also wrapped it in a catch statement to prevent anything being shutdown from an error
